# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = SMTnTupAnalysis
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS = -g
PACKAGE_LDFLAGS  =
PACKAGE_BINFLAGS = -g
PACKAGE_DEP      = FakesMacros WjetsCorrections
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
